name: Deploy environment

on: [push, workflow_dispatch]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.filter.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            environment:
              - 'environment/**'

  deploy-environment:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.environment == 'true' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./environment/
          push: true
          tags: vexdev/fission-kotlin-env:latest